In [1]:
# to install numpy
import sys
!{sys.executable} -m pip install numpy

In [2]:
import numpy as np

### Elementwise operation

1. Basic operations

    with scalars

In [3]:
a = np.array([1,2,3,4])
print(a)

b = a + 1
print(b)

[1 2 3 4]
[2 3 4 5]


In [4]:
a ** 2

array([ 1,  4,  9, 16])

#### All arithematic operates elementwise

In [5]:
b = np.ones(4) + 1
print(b)

a - b

[2. 2. 2. 2.]


array([-1.,  0.,  1.,  2.])

In [6]:
a * b

array([2., 4., 6., 8.])

In [7]:
# Matrix multiplication

c = np.diag([1,2,3,4])

print(c*c)
print("*********")
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
*********
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


comparisions

In [8]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

a == b

array([False, False, False, False])

In [9]:
a > b

array([False, False, False, False])

In [10]:
a < b

array([ True,  True,  True,  True])

In [11]:
# array wise comparision
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.array([1,2,3,4])

np.array_equal(a,b)

False

In [12]:
np.array_equal(a,c)

True

Logical Operations

In [13]:
a = np.array([1,1,0,0], dtype = bool)
b = np.array([1,0,1,0], dtype = bool)

np.logical_and(a,b)


array([ True, False, False, False])

In [14]:
np.logical_or(a,b)

array([ True,  True,  True, False])

Transcandental function

In [15]:
a = np.arange(5)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [16]:
np.log(a)

/srv/conda/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [17]:
a = np.arange(1,4) #evaluates e^x for each element in a given input
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692])

Shape Mismatch

In [18]:
a = np.arange(4)
b = a + np.array([1,2,1,2])
print(b)
a + np.array([1,2])

[1 3 3 5]


ValueError: operands could not be broadcast together with shapes (4,) (2,) 

### Basic Reduction

computing sums

In [ ]:
x = np.array([1,2,3,4])
np.sum(x)

In [ ]:
# sum by rows and columns

x = np.array([[1,2],[3,4]])
print(x)

In [ ]:
x.sum(axis = 0)

In [ ]:
x.sum(axis = 1)

other reductions

In [ ]:
x = np.array([1,2,3])
x.min()

In [ ]:
x.max()

In [ ]:
x.argmin() # index of min value

In [ ]:
x.argmax() #index of maximum element

Logical Operations

In [ ]:
np.all([True,True,False])

In [ ]:
# Note: can be used for array comparisions

a = np.zeros((3,3))
np.any(a != 0)

In [ ]:
print(np.all(a == a))

b = np.arange(3)
c = np.arange(3)

print(np.all(a == c))

In [ ]:
a = np.array([1,2,3,4])
b = np.array([1,1,1,1])
c = np.array([3,4,5,6])

((a < c) & (b < c)).all()

Statistics

In [ ]:
x = np.array([1,2,3,4,5,6])
y = np.array([[1,2,3],[5,4,6]])

x.mean()

In [ ]:
np.median(x)

In [ ]:
np.median(y, axis = -1) # last axis

In [ ]:
x.std() # standard deviation

Example

Data in populations.txt describes the populations of hares and lynxes (and carrots) in northern Canada during 20 years.

In [20]:
# load data in numpy array object

data = np.loadtxt("populations.txt")
print(data)

[[ 1900. 30000.  4000. 48300.]
 [ 1901. 47200.  6100. 48200.]
 [ 1902. 70200.  9800. 41500.]
 [ 1903. 77400. 35200. 38200.]
 [ 1904. 36300. 59400. 40600.]
 [ 1905. 20600. 41700. 39800.]
 [ 1906. 18100. 19000. 38600.]
 [ 1907. 21400. 13000. 42300.]
 [ 1908. 22000.  8300. 44500.]
 [ 1909. 25400.  9100. 42100.]
 [ 1910. 27100.  7400. 46000.]
 [ 1911. 40300.  8000. 46800.]
 [ 1912. 57000. 12300. 43800.]
 [ 1913. 76600. 19500. 40900.]
 [ 1914. 52300. 45700. 39400.]
 [ 1915. 19500. 51100. 39000.]
 [ 1916. 11200. 29700. 36700.]
 [ 1917.  7600. 15800. 41800.]
 [ 1918. 14600.  9700. 43300.]
 [ 1919. 16200. 10100. 41300.]
 [ 1920. 24700.  8600. 47300.]]


In [21]:
print(data.T)

[[ 1900.  1901.  1902.  1903.  1904.  1905.  1906.  1907.  1908.  1909.
   1910.  1911.  1912.  1913.  1914.  1915.  1916.  1917.  1918.  1919.
   1920.]
 [30000. 47200. 70200. 77400. 36300. 20600. 18100. 21400. 22000. 25400.
  27100. 40300. 57000. 76600. 52300. 19500. 11200.  7600. 14600. 16200.
  24700.]
 [ 4000.  6100.  9800. 35200. 59400. 41700. 19000. 13000.  8300.  9100.
   7400.  8000. 12300. 19500. 45700. 51100. 29700. 15800.  9700. 10100.
   8600.]
 [48300. 48200. 41500. 38200. 40600. 39800. 38600. 42300. 44500. 42100.
  46000. 46800. 43800. 40900. 39400. 39000. 36700. 41800. 43300. 41300.
  47300.]]


In [22]:
years, hares, lynes, carrots = data.T
print("Year:" ,years)
print("*****************")
print("hares:",hares)
print("*****************")
print("ltnes:",lynes)
print("*****************")
print("carrot:",carrots)

Year: [1900. 1901. 1902. 1903. 1904. 1905. 1906. 1907. 1908. 1909. 1910. 1911.
 1912. 1913. 1914. 1915. 1916. 1917. 1918. 1919. 1920.]
*****************
hares: [30000. 47200. 70200. 77400. 36300. 20600. 18100. 21400. 22000. 25400.
 27100. 40300. 57000. 76600. 52300. 19500. 11200.  7600. 14600. 16200.
 24700.]
*****************
ltnes: [ 4000.  6100.  9800. 35200. 59400. 41700. 19000. 13000.  8300.  9100.
  7400.  8000. 12300. 19500. 45700. 51100. 29700. 15800.  9700. 10100.
  8600.]
*****************
carrot: [48300. 48200. 41500. 38200. 40600. 39800. 38600. 42300. 44500. 42100.
 46000. 46800. 43800. 40900. 39400. 39000. 36700. 41800. 43300. 41300.
 47300.]


In [23]:
population = data[:,1:] # all rows and all columns from index 1
print(population)

[[30000.  4000. 48300.]
 [47200.  6100. 48200.]
 [70200.  9800. 41500.]
 [77400. 35200. 38200.]
 [36300. 59400. 40600.]
 [20600. 41700. 39800.]
 [18100. 19000. 38600.]
 [21400. 13000. 42300.]
 [22000.  8300. 44500.]
 [25400.  9100. 42100.]
 [27100.  7400. 46000.]
 [40300.  8000. 46800.]
 [57000. 12300. 43800.]
 [76600. 19500. 40900.]
 [52300. 45700. 39400.]
 [19500. 51100. 39000.]
 [11200. 29700. 36700.]
 [ 7600. 15800. 41800.]
 [14600.  9700. 43300.]
 [16200. 10100. 41300.]
 [24700.  8600. 47300.]]


In [24]:
# sample standard deviation
population.std(axis = 0)

array([20897.90645809, 16254.59153691,  3322.50622558])

In [25]:
# which species has the highest population each year

population.max(axis = 1)

array([48300., 48200., 70200., 77400., 59400., 41700., 38600., 42300.,
       44500., 42100., 46000., 46800., 57000., 76600., 52300., 51100.,
       36700., 41800., 43300., 41300., 47300.])

In [26]:
population.argmax(axis = 1)

array([2, 2, 0, 0, 1, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 1, 2, 2, 2, 2, 2])

In [27]:
# species having population minimum each year

population.min(axis = 1)

array([ 4000.,  6100.,  9800., 35200., 36300., 20600., 18100., 13000.,
        8300.,  9100.,  7400.,  8000., 12300., 19500., 39400., 19500.,
       11200.,  7600.,  9700., 10100.,  8600.])

In [28]:
population.argmin(axis = 1)

array([1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 0, 0, 0, 1, 1, 1])

In [74]:
# To get the species having maximum population with year and name
max_agr = population.argmax(axis = 0)
print("Index value:",max_agr)
max_val = population.max(axis = 0)
max_amg_all = np.max(max_val)

for i in range(len(max_agr)):
    if(max_amg_all == population[max_agr[i]][i]):
        print("Max population",population[max_agr[i]][i])
        if(population[max_agr[i]][i] in hares):
            print("Hares")
            print("In the year:",years[max_agr[i]])
        elif(population[max_agr[i]][i] in lynes):
            print("Lyanex")
            print("In the year:",years[max_agr[i]])
        elif(population[max_agr[i]][i] in carrots):
            print("Carrots")
            print("In the year:",years[max_agr[i]])
        else:
            print("Not proper")


Index value: [3 4 0]
Max population 77400.0
Hares
In the year: 1903.0


### Broadcasting

Basic operations on numpy arrays (addition, etc.) are elementwise

This works on arrays of the same size. Nevertheless, It’s also possible to do operations on arrays of different sizes if NumPy can transform these arrays so that they all have the same size: this conversion is called broadcasting.

The image below gives an example of broadcasting:

In [ ]:
a = np.tile(np.arange(0,40,10),(3,1)) # having 3 rows and one colum to replicate
print(a)

print("***********")

a = a.T
print(a)

In [ ]:
b = np.array([0,1,2])
print(b)

In [ ]:
a + b

In [ ]:
a = np.arange(0,40,10)
a.shape

In [ ]:
a = a[:,np.newaxis]
print(a)

In [ ]:
a + b

### Array shape manipulation

#### Flattening

In [94]:
a = np.array([[1,2,3],[4,5,6]])
print(np.ndim(a))
print(np.shape(a))
b = a.ravel()
print(b)
print(np.ndim(b))

2
(2, 3)
[1 2 3 4 5 6]
1


In [95]:
b = a.T
print(b)

[[1 4]
 [2 5]
 [3 6]]


In [96]:
b = a.T.ravel()
print(b)

[1 4 2 5 3 6]


#### Reshaping

The inverse operation to flattening

In [97]:
print(a.shape)
print(a)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [98]:
b = a.ravel()
print(b)

[1 2 3 4 5 6]


In [99]:
b = b.reshape(3,2)
print(b)
print(a)

[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]


In [100]:
b[0,0] = 100
print(a)

[[100   2   3]
 [  4   5   6]]


**Note and Beware: reshape may also return a copy!:**

In [114]:
a = np.zeros((3,2))
b = a.T.reshape(3*2) #this makes the array as a 1-D as we are passing a single value 6. 
# work similar to ravel, except for the returning of the copy sometimes
print("b after reshaping")
print(b)
print("******************")
b[0] = 10
print("b after assigning 10 to the 0th index")
print(b)
print("******************")
print("a after assigning value 10 to b, to check if a has changed")
print(a)
print("******************")
b = a.reshape(2,3)
print("b after reshape")
print(b)
print("******************")
b[0][1] = 100
print("a after assigning value 100 to b, to check if a has changed")
print(a)

b after reshaping
[0. 0. 0. 0. 0. 0.]
******************
b after assigning 10 to the 0th index
[10.  0.  0.  0.  0.  0.]
******************
a after assigning value 10 to b, to check if a has changed
[[0. 0.]
 [0. 0.]
 [0. 0.]]
******************
b after reshape
[[0. 0. 0.]
 [0. 0. 0.]]
******************
a after assigning value 100 to b, to check if a has changed
[[  0. 100.]
 [  0.   0.]
 [  0.   0.]]


#### Adding a Dimension

Indexing with the np.newaxis object allows us to add an axis to an array

newaxis is used to increase the dimension of the existing array by one more dimension, when used once. Thus,

1D array will become 2D array

2D array will become 3D array

3D array will become 4D array and so on

In [115]:
z = np.array([1,2,3])
print(z)

[1 2 3]


In [118]:
z = z[:,np.newaxis]
print(z)

[[1]
 [2]
 [3]]


#### Dimension Shuffling

In [119]:
a = np.arange(4*3*2).reshape(4,3,2)
print(a)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]


In [120]:
print(a.shape)

(4, 3, 2)


In [123]:
print(a[0,1,1])

3


#### Resizing

In [124]:
a = np.arange(4)
a.resize((8,))
print(a)

[0 1 2 3 0 0 0 0]


However, it must not be referred to somewhere else:

In [127]:
b = a
a.resize((4,))

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [129]:
# reshape is possible, but resize is not possible as we are manipulating the values
a.reshape(2,2,2)

array([[[0, 1],
        [2, 3]],

       [[0, 0],
        [0, 0]]])

#### Sorting Data

In [133]:
# sorting along an axis
a = np.array([[5,4,6],[2,3,10]])
b = np.sort(a,axis = 0) # columnwise sort
print(b)

c = np.sort(a,axis = 1) # rowwise sort
print(c)


[[ 2  3  6]
 [ 5  4 10]]
[[ 4  5  6]
 [ 2  3 10]]


In [134]:
# in-place sort
a.sort(axis = 1)
print(a)

[[ 4  5  6]
 [ 2  3 10]]


In [135]:
# sorting with fancy indexing

a = np.array([4,3,2,1])
j = np.argsort(a)
print(j)

[3 2 1 0]


In [143]:
a[j]#possible only with single dimension array

array([1, 2, 3, 4])

In [148]:
z = np.array([[2,3,4],[9,1,45]])
x = np.reshape(z,(3*2))
y = np.argsort(x) # columnwise
print(y)

[4 0 1 2 3 5]
