In [1]:
import numpy as np

### Elementwise operation

1. Basic operations

    with scalars

In [5]:
a = np.array([1,2,3,4])
print(a)

b = a + 1
print(b)

[1 2 3 4]
[2 3 4 5]


In [6]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

#### All arithematic operates elementwise

In [8]:
b = np.ones(4) + 1
print(b)

a - b

[2. 2. 2. 2.]


array([-1.,  0.,  1.,  2.])

In [9]:
a * b

array([2., 4., 6., 8.])

In [11]:
# Matrix multiplication

c = np.diag([1,2,3,4])

print(c*c)
print("*********")
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
*********
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


comparisions

In [12]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

a == b

array([False, False, False, False])

In [13]:
a > b

array([False, False, False, False])

In [14]:
a < b

array([ True,  True,  True,  True])

In [15]:
# array wise comparision
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.array([1,2,3,4])

np.array_equal(a,b)

False

In [16]:
np.array_equal(a,c)

True

Logical Operations

In [17]:
a = np.array([1,1,0,0], dtype = bool)
b = np.array([1,0,1,0], dtype = bool)

np.logical_and(a,b)


array([ True, False, False, False])

In [18]:
np.logical_or(a,b)

array([ True,  True,  True, False])

Transcandental function

In [19]:
a = np.arange(5)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [20]:
np.log(a)

C:\anaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [22]:
a = np.arange(1,4) #evaluates e^x for each element in a given input
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692])

Shape Mismatch

In [24]:
a = np.arange(4)
b = a + np.array([1,2,1,2])
print(b)
a + np.array([1,2])

[1 3 3 5]


ValueError: operands could not be broadcast together with shapes (4,) (2,) 

### Basic Reduction

computing sums

In [25]:
x = np.array([1,2,3,4])
np.sum(x)

10

In [26]:
# sum by rows and columns

x = np.array([[1,2],[3,4]])
print(x)

[[1 2]
 [3 4]]


In [27]:
x.sum(axis = 0)

array([4, 6])

In [28]:
x.sum(axis = 1)

array([3, 7])

other reductions

In [29]:
x = np.array([1,2,3])
x.min()

1

In [30]:
x.max()

3

In [31]:
x.argmin() # index of min value

0

In [33]:
x.argmax() #index of maximum element

2

Logical Operations

In [34]:
np.all([True,True,False])

False

In [35]:
# Note: can be used for array comparisions

a = np.zeros((3,3))
np.any(a != 0)

False

In [38]:
print(np.all(a == a))

b = np.arange(3)
c = np.arange(3)

print(np.all(a == c))

True
False


In [39]:
a = np.array([1,2,3,4])
b = np.array([1,1,1,1])
c = np.array([3,4,5,6])

((a < c) & (b < c)).all()

True

Statistics

In [40]:
x = np.array([1,2,3,4,5,6])
y = np.array([[1,2,3],[5,4,6]])

x.mean()

3.5

In [41]:
np.median(x)

3.5

In [44]:
np.median(y, axis = -1) # last axis

array([2., 5.])

In [46]:
x.std() # standard deviation

1.707825127659933

Example

Data in populations.txt describes the populations of hares and lynxes (and carrots) in northern Canada during 20 years.

In [47]:
# load data in numpy array object

data = np.loadtxt("populations.txt")
print(data)

[[ 1900. 30000.  4000. 48300.]
 [ 1901. 47200.  6100. 48200.]
 [ 1902. 70200.  9800. 41500.]
 [ 1903. 77400. 35200. 38200.]
 [ 1904. 36300. 59400. 40600.]
 [ 1905. 20600. 41700. 39800.]
 [ 1906. 18100. 19000. 38600.]
 [ 1907. 21400. 13000. 42300.]
 [ 1908. 22000.  8300. 44500.]
 [ 1909. 25400.  9100. 42100.]
 [ 1910. 27100.  7400. 46000.]
 [ 1911. 40300.  8000. 46800.]
 [ 1912. 57000. 12300. 43800.]
 [ 1913. 76600. 19500. 40900.]
 [ 1914. 52300. 45700. 39400.]
 [ 1915. 19500. 51100. 39000.]
 [ 1916. 11200. 29700. 36700.]
 [ 1917.  7600. 15800. 41800.]
 [ 1918. 14600.  9700. 43300.]
 [ 1919. 16200. 10100. 41300.]
 [ 1920. 24700.  8600. 47300.]]


In [48]:
print(data.T)

[[ 1900.  1901.  1902.  1903.  1904.  1905.  1906.  1907.  1908.  1909.
   1910.  1911.  1912.  1913.  1914.  1915.  1916.  1917.  1918.  1919.
   1920.]
 [30000. 47200. 70200. 77400. 36300. 20600. 18100. 21400. 22000. 25400.
  27100. 40300. 57000. 76600. 52300. 19500. 11200.  7600. 14600. 16200.
  24700.]
 [ 4000.  6100.  9800. 35200. 59400. 41700. 19000. 13000.  8300.  9100.
   7400.  8000. 12300. 19500. 45700. 51100. 29700. 15800.  9700. 10100.
   8600.]
 [48300. 48200. 41500. 38200. 40600. 39800. 38600. 42300. 44500. 42100.
  46000. 46800. 43800. 40900. 39400. 39000. 36700. 41800. 43300. 41300.
  47300.]]


In [50]:
years, hares, lynes, carrots = data.T
print("Year:" ,years)
print("hares:",hares)
print("ltnes:",lynes)
print("carrot:",carrots)

Year: [1900. 1901. 1902. 1903. 1904. 1905. 1906. 1907. 1908. 1909. 1910. 1911.
 1912. 1913. 1914. 1915. 1916. 1917. 1918. 1919. 1920.]
hares: [30000. 47200. 70200. 77400. 36300. 20600. 18100. 21400. 22000. 25400.
 27100. 40300. 57000. 76600. 52300. 19500. 11200.  7600. 14600. 16200.
 24700.]
ltnes: [ 4000.  6100.  9800. 35200. 59400. 41700. 19000. 13000.  8300.  9100.
  7400.  8000. 12300. 19500. 45700. 51100. 29700. 15800.  9700. 10100.
  8600.]
carrot: [48300. 48200. 41500. 38200. 40600. 39800. 38600. 42300. 44500. 42100.
 46000. 46800. 43800. 40900. 39400. 39000. 36700. 41800. 43300. 41300.
 47300.]


In [56]:
population = data[:,1:]
print(population)

[[30000.  4000. 48300.]
 [47200.  6100. 48200.]
 [70200.  9800. 41500.]
 [77400. 35200. 38200.]
 [36300. 59400. 40600.]
 [20600. 41700. 39800.]
 [18100. 19000. 38600.]
 [21400. 13000. 42300.]
 [22000.  8300. 44500.]
 [25400.  9100. 42100.]
 [27100.  7400. 46000.]
 [40300.  8000. 46800.]
 [57000. 12300. 43800.]
 [76600. 19500. 40900.]
 [52300. 45700. 39400.]
 [19500. 51100. 39000.]
 [11200. 29700. 36700.]
 [ 7600. 15800. 41800.]
 [14600.  9700. 43300.]
 [16200. 10100. 41300.]
 [24700.  8600. 47300.]]


In [58]:
# sample standard deviation
population.std(axis = 0)

array([20897.90645809, 16254.59153691,  3322.50622558])

In [60]:
# which species has the highest population eaxh year

population.max(axis = 1)

array([48300., 48200., 70200., 77400., 59400., 41700., 38600., 42300.,
       44500., 42100., 46000., 46800., 57000., 76600., 52300., 51100.,
       36700., 41800., 43300., 41300., 47300.])

In [61]:
population.argmax(axis = 1)

array([2, 2, 0, 0, 1, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 1, 2, 2, 2, 2, 2],
      dtype=int64)

In [62]:
# species having population minimum each year

population.min(axis = 1)

array([ 4000.,  6100.,  9800., 35200., 36300., 20600., 18100., 13000.,
        8300.,  9100.,  7400.,  8000., 12300., 19500., 39400., 19500.,
       11200.,  7600.,  9700., 10100.,  8600.])

In [63]:
population.argmin(axis = 1)

array([1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 0, 0, 0, 1, 1, 1],
      dtype=int64)

### Broadcasting

Basic operations on numpy arrays (addition, etc.) are elementwise

This works on arrays of the same size. Nevertheless, It’s also possible to do operations on arrays of different sizes if NumPy can transform these arrays so that they all have the same size: this conversion is called broadcasting.

The image below gives an example of broadcasting:

In [70]:
a = np.tile(np.arange(0,40,10),(3,1)) # having 3 rows and one colum to replicate
print(a)

print("***********")

a = a.T
print(a)

[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]
***********
[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]


In [68]:
b = np.array([0,1,2])
print(b)

[0 1 2]


In [71]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [73]:
a = np.arange(0,40,10)
a.shape

(4,)

In [74]:
a = a[:,np.newaxis]
print(a)

[[ 0]
 [10]
 [20]
 [30]]


In [75]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

### Array shape manipulation